variables:
  buildConfiguration: 'Release'
  buildVersion: $[ counter('constant', 94) ]
  versionPrefix: '2.1'
  versionSuffix: 'alpha'
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
